### ISSUE TITLE
Link to article

### ISSUE THREAD

**Issue by Kochise** [fabiensanglard/Another-World-Bytecode-Interpreter#20]
Top link is 404, here's the correct link on your recent articles : http://fabiensanglard.net/another_world_polygons/index.html

Good job and happy new year.

**Comment by fabiensanglard** [comment]
Which link?

**Comment by Kochise** [comment]
Header :
"Fabother World" an interpreter for Another World (Out of this world). http://fabiensanglard.net/anotherWorld <- THIS LINK

**Comment by fabiensanglard** [comment]
Sorry but I cannot find where the link is wrong.

**Comment by Kochise** [comment]
https://github.com/fabiensanglard/Another-World-Bytecode-Interpreter

The link at the top of the page !!!!!!!!!

**Comment by fabiensanglard** [comment]
Oh right, I get it now :P 

Thanks for reporting the issue, it has now been addressed.
