### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by Zibri** [fabiensanglard/Another-World-Bytecode-Interpreter#21]
> make
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c bank.cpp -o bank.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c file.cpp -o file.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c engine.cpp -o engine.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c mixer.cpp -o mixer.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c resource.cpp -o resource.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c parts.cpp -o parts.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c vm.cpp -o vm.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c serializer.cpp -o serializer.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c sfxplayer.cpp -o sfxplayer.o
> sfxplayer.cpp: In constructor ‘SfxPlayer::SfxPlayer(Mixer*, Resource*, System*)’:
> sfxplayer.cpp:26:61: warning: declaration of ‘res’ shadows a member of ‘SfxPlayer’ [-Wshadow]
>  SfxPlayer::SfxPlayer(Mixer *mix, Resource *res, System *stub)
>                                                              ^
> In file included from sfxplayer.cpp:19:0:
> sfxplayer.h:57:12: note: shadowed declaration is here
>   Resource *res;
>             ^~~
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c staticres.cpp -o staticres.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c util.cpp -o util.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c video.cpp -o video.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c main.cpp -o main.o
> g++ -Os -g -std=gnu++98 -fno-rtti -fno-exceptions -Wall -Wno-unknown-pragmas -Wshadow -Wundef -Wwrite-strings -Wnon-virtual-dtor -Wno-multichar `sdl2-config --cflags` -DAUTO_DETECT_PLATFORM -MMD -c sysImplementation.cpp -o sysImplementation.o
> sysImplementation.cpp:304:1: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++11-compat]
>  return nullptr;
>  ^~~~~~
> sysImplementation.cpp: In member function ‘virtual void* SDLStub::addTimer(uint32_t, System::TimerCallback, void*)’:
> sysImplementation.cpp:304:8: error: ‘nullptr’ was not declared in this scope
>  return nullptr;
>         ^~~~~~~
> Makefile:26: recipe for target 'sysImplementation.o' failed
> make: *** [sysImplementation.o] Error 1

**Comment by fabiensanglard** [comment]
Can you try to opem Makefile and replace:
-std=gnu++98
with
-std=c++11

**Comment by Zibri** [comment]
nevermind I just did:

sed -i "s/3.15/3.10/" CMakeLists.txt
cmake .
make

and it compiled.
