### ISSUE TITLE
Strings shouldnt be hardcoded in the game-engine

### ISSUE THREAD

**Issue by felipesanches** [fabiensanglard/Another-World-Bytecode-Interpreter#7]
The drawstrings opcode receives a string id and then reads it from a list of hardcoded strings in the interpreter. I think that the strings should be fetched as game resources somehow. Any idea how was that done in the original game?

**Comment by fabiensanglard** [comment]
Same comment here. Did you ever figure it out? The GBA also have the strings hard-coded.

**Comment by felipesanches** [comment]
I haven't yet figured it out, but I stumbled on this question again today: https://github.com/felipesanches/AnotherWorld_VMTools/issues/15
