### ISSUE TITLE
Figure out what's in the UNKNOWN 0x11 resource

### ISSUE THREAD

**Issue by felipesanches** [fabiensanglard/Another-World-Bytecode-Interpreter#9]
There is one unknown resource with type=6 and id=0x11.

R:0x11, RT_UNKNOWN        size=25108 (compacted gain=25%)

We should figure out what's inside. My guess is it might contain game specific strings such as "Good evening, professor." as well as font data and maybe something else.

**Comment by fabiensanglard** [comment]
Closing unless you ever figured it out.
